const fs = require("fs/promises");
const path = require("path");
const { spawnSync } = require("child_process");

const ROOT_DIR = path.join(__dirname, "..");
const SEED_DIR = path.join(ROOT_DIR, "data", "seed");
const SQL_DIR = path.join(ROOT_DIR, "supabase", "sql");

const INPUT_JSONS = [
  path.join(SEED_DIR, "mandarin_1000.json"),
  path.join(SEED_DIR, "french_1000.json"),
  path.join(SEED_DIR, "english_1000.json"),
];

const OUTPUT_JSON = path.join(SEED_DIR, "all_languages_3000.json");
const OUTPUT_CSV = path.join(SEED_DIR, "all_languages_3000.csv");
const OUTPUT_SQL = path.join(SQL_DIR, "004_upsert_all_languages.sql");

function runNpmScript(scriptName) {
  const command = process.platform === "win32" ? "npm.cmd" : "npm";
  const result = spawnSync(command, ["run", scriptName], {
    cwd: ROOT_DIR,
    stdio: "inherit",
  });

  if (result.status !== 0) {
    throw new Error(`npm run ${scriptName} failed with code ${result.status}`);
  }
}

function normalizeRow(row) {
  const languageCode = String(row.language_code || "")
    .trim()
    .toLowerCase();
  const word = String(row.word || "").trim();
  const pinyin = String(row.pinyin || "").trim();
  const meaningEn = String(row.meaning_en || row.meaning || "").trim();
  const frequencyRank = Number(row.frequency_rank || 0);
  const sourceFreq = String(row.source_freq || "").trim();
  const sourceDict = String(row.source_dict || "").trim();

  if (!languageCode || !word || !meaningEn || !Number.isFinite(frequencyRank)) {
    return null;
  }

  return {
    language_code: languageCode,
    word,
    pinyin,
    meaning_en: meaningEn,
    frequency_rank: frequencyRank,
    source_freq: sourceFreq,
    source_dict: sourceDict,
  };
}

function escapeCsv(value) {
  const raw = String(value ?? "");
  if (raw.includes(",") || raw.includes('"') || raw.includes("\n")) {
    return `"${raw.replace(/"/g, '""')}"`;
  }
  return raw;
}

function escapeSqlLiteral(value) {
  return String(value ?? "").replace(/'/g, "''");
}

function chunk(array, size) {
  const chunks = [];
  for (let index = 0; index < array.length; index += size) {
    chunks.push(array.slice(index, index + size));
  }
  return chunks;
}

function buildInsertStatement(rows) {
  const valuesSql = rows
    .map((row) => {
      return `('${escapeSqlLiteral(row.language_code)}', '${escapeSqlLiteral(row.word)}', '${escapeSqlLiteral(row.pinyin)}', '${escapeSqlLiteral(row.meaning_en)}', ${row.frequency_rank}, '${escapeSqlLiteral(row.source_freq)}', '${escapeSqlLiteral(row.source_dict)}')`;
    })
    .join(",\n  ");

  return `insert into public.learning_words (\n  language_code,\n  word,\n  pinyin,\n  meaning_en,\n  frequency_rank,\n  source_freq,\n  source_dict\n)\nvalues\n  ${valuesSql}\non conflict (language_code, word)\ndo update set\n  pinyin = excluded.pinyin,\n  meaning_en = excluded.meaning_en,\n  frequency_rank = excluded.frequency_rank,\n  source_freq = excluded.source_freq,\n  source_dict = excluded.source_dict,\n  updated_at = now();`;
}

async function writeCombinedJson(rows) {
  await fs.writeFile(OUTPUT_JSON, JSON.stringify(rows, null, 2), "utf8");
}

async function writeCombinedCsv(rows) {
  const header =
    "language_code,word,pinyin,meaning_en,frequency_rank,source_freq,source_dict";

  const lines = rows.map((row) => {
    return [
      row.language_code,
      row.word,
      row.pinyin,
      row.meaning_en,
      row.frequency_rank,
      row.source_freq,
      row.source_dict,
    ]
      .map(escapeCsv)
      .join(",");
  });

  await fs.writeFile(OUTPUT_CSV, [header, ...lines].join("\n"), "utf8");
}

async function writeUpsertSql(rows) {
  const statements = chunk(rows, 500).map(buildInsertStatement);

  const sql = [
    "-- Auto-generated by scripts/extract_all_seeds.js",
    "-- Upserts all FR/EN/ZH seed rows into public.learning_words",
    "",
    "begin;",
    ...statements,
    "commit;",
    "",
  ].join("\n\n");

  await fs.writeFile(OUTPUT_SQL, sql, "utf8");
}

async function main() {
  console.log("[all-seeds] Running language extractors...");
  runNpmScript("extract:mandarin");
  runNpmScript("extract:french");
  runNpmScript("extract:english");

  console.log("[all-seeds] Reading seed JSON files...");
  const loaded = [];
  for (const filePath of INPUT_JSONS) {
    const raw = await fs.readFile(filePath, "utf8");
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) continue;

    for (const entry of parsed) {
      const normalized = normalizeRow(entry);
      if (normalized) loaded.push(normalized);
    }
  }

  if (loaded.length === 0) {
    throw new Error("No seed rows found after extraction.");
  }

  loaded.sort((a, b) => {
    const langCompare = a.language_code.localeCompare(b.language_code);
    if (langCompare !== 0) return langCompare;
    return a.frequency_rank - b.frequency_rank;
  });

  await fs.mkdir(SEED_DIR, { recursive: true });
  await fs.mkdir(SQL_DIR, { recursive: true });

  console.log("[all-seeds] Writing combined outputs...");
  await writeCombinedJson(loaded);
  await writeCombinedCsv(loaded);
  await writeUpsertSql(loaded);

  console.log(`[all-seeds] Wrote JSON: ${OUTPUT_JSON}`);
  console.log(`[all-seeds] Wrote CSV: ${OUTPUT_CSV}`);
  console.log(`[all-seeds] Wrote SQL: ${OUTPUT_SQL}`);
  console.log(`[all-seeds] Total rows: ${loaded.length}`);
}

main().catch((error) => {
  console.error("[all-seeds] Failed:", error.message);
  process.exit(1);
});
